PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-danai#>
    {
        ?newFarm a was:Farm.
    }.
} WHERE {
	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-danai#farm-", strUUID())) AS ?newFarm)
}
