PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>
PREFIX wotsec: <https://www.w3.org/2019/wot/security#>
PREFIX htv: <http://www.w3.org/2011/http#>
PREFIX hctl: <https://www.w3.org/2019/wot/hypermedia#>
PREFIX js: <https://www.w3.org/2019/wot/json-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#>
    {
        ?newSection1 was:hasDimension ?newCoordinate1.
        ?newSection2 was:hasDimension ?newCoordinate2.
        ?newSection3 was:hasDimension ?newCoordinate3.
        ?newSection4 was:hasDimension ?newCoordinate4.

        ?newCoordinate1 a was:Coordinates ;
            was:hasDimension "0,0,1,1" .
        ?newCoordinate2 a was:Coordinates ;
            was:hasDimension "1,0,2,1" .
        ?newCoordinate3 a was:Coordinates ;
            was:hasDimension "0,1,1,2" .
        ?newCoordinate4 a was:Coordinates ;
            was:hasDimension "1,1,2,2" .
    }.
} WHERE {
    ?newSection1 a was:Section.
    ?newSection2 a was:Section.
    ?newSection3 a was:Section.
    ?newSection4 a was:Section.
    
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#coordinate-", 1)) AS ?newCoordinate1)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#coordinate-", 2)) AS ?newCoordinate2)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#coordinate-", 3)) AS ?newCoordinate3)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#coordinate-", 4)) AS ?newCoordinate4)
}
