PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>
PREFIX wotsec: <https://www.w3.org/2019/wot/security#>
PREFIX htv: <http://www.w3.org/2011/http#>
PREFIX hctl: <https://www.w3.org/2019/wot/hypermedia#>
PREFIX js: <https://www.w3.org/2019/wot/json-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#>
    {
        ?wheatcrop1 a was:WheatCrop.
        ?wheatcrop2 a was:WheatCrop.
        ?corncrop1 a was:CornCrop.
        ?corncrop2 a was:CornCrop.
        
        ?section1 was:grows ?wheatcrop1.
        ?section2 was:grows ?wheatcrop2.
        ?section3 was:grows ?corncrop1.
        ?section4 was:grows ?corncrop2.

    }.
} WHERE {
    ?section1 a was:Section.
    ?section2 a was:Section.
    ?section3 a was:Section.
    ?section4 a was:Section.
	?section1 was:hasDimensions ( [ a was:Coordinates; was:x1 "0"^^xsd:integer; was:y1 "0"^^xsd:integer; was:x2 "1"^^xsd:integer; was:y2 "1"^^xsd:integer ]
                     ) .
    ?section2 was:hasDimensions ( [ a was:Coordinate; was:x1 "1"^^xsd:integer; was:y1 "0"^^xsd:integer; was:x2 "2"^^xsd:integer; was:y2 "1"^^xsd:integer ]
                     ) .
    ?section3 was:hasDimensions ( [ a was:Coordinate; was:x1 "0"^^xsd:integer; was:y1 "1"^^xsd:integer; was:x2 "1"^^xsd:integer; was:y2 "2"^^xsd:integer ]
                     ) .
    ?section4 was:hasDimensions ( [ a was:Coordinate; was:x1 "1"^^xsd:integer; was:y1 "1"^^xsd:integer; was:x2 "2"^^xsd:integer; was:y2 "2"^^xsd:integer ]
                     ) .
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#wheatcrop-", '1')) AS ?wheatcrop1)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#wheatcrop-", '2')) AS ?wheatcrop2)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#corncrop-", '1')) AS ?corncrop1)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#corncrop-", '2')) AS ?corncrop2)
}
