PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>
PREFIX wotsec: <https://www.w3.org/2019/wot/security#>
PREFIX htv: <http://www.w3.org/2011/http#>
PREFIX hctl: <https://www.w3.org/2019/wot/hypermedia#>
PREFIX js: <https://www.w3.org/2019/wot/json-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#>
    {
        ?crop1 was:hasMoistureLevel 85.
        ?crop2 was:hasMoistureLevel 95.
        ?wheat1 was:hasMoistureLevel 115.
        ?wheat2 was:hasMoistureLevel 125.
    }.
} WHERE {
	?crop1 a was:Crop.
    ?crop2 a was:Crop.
    ?wheat1 a was:Wheat.
    ?wheat2 a was:Wheat.
}
