PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>

SELECT ?tractor WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-xuemei#ffarm-e7108aee-03b7-4c96-bcc5-787e142bc885> as ?farm)
   ?farm a was:Farm.    
   ?farm hmas:contains ?tractor.
   ?tractor a was:Tractor.
 }
}
